# Generated by Django 4.1.4 on 2022-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('dateofbirth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=10, null=True)),
                ('grade', models.CharField(choices=[('초', '초'), ('중', '중'), ('고', '고')], max_length=10, null=True)),
                ('note', models.TextField()),
            ],
        ),
    ]
